# Generated by Django 5.0.7 on 2025-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
