# Generated by Django 5.1.6 on 2025-05-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_alter_invoice_supplier_dds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DDS',
            field=models.CharField(choices=[(20, 20), (9, 9), (0, 0)], default=20, max_length=20),
        ),
    ]
