# Generated by Django 5.0.7 on 2025-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0010_remove_invoice_supplier_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DDS',
            field=models.CharField(default='20', max_length=20),
        ),
    ]
