# Generated by Django 5.1.6 on 2025-05-17 13:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_app', '0005_order_order_status_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eik', models.CharField(max_length=13, unique=True)),
                ('dds', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mol', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_eik', models.CharField(default='000000000', max_length=13, unique=True)),
                ('supplier_dds', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(default='firma_firma', max_length=100)),
                ('supplier_address', models.CharField(default='goce delchev 30', max_length=100)),
                ('supplier_mol', models.CharField(default='Pavel Kalchishkov', max_length=100)),
                ('supplier_phone_number', models.CharField(default='089 860 2996', max_length=100)),
                ('supplier_email', models.CharField(default='pavelkalchishkov@gmail.com', max_length=100)),
                ('DDS', models.CharField(choices=[('20%', '20%'), ('9%', '9%'), ('0%', '0%')], default='20%', max_length=20)),
                ('date', models.DateField(default=datetime.date(2025, 5, 17))),
                ('comment', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('whole_price_without_dds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('whole_price_with_dds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice_app.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders_app.order')),
            ],
        ),
    ]
