# Generated by Django 5.1.6 on 2025-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='supplier_dds',
            field=models.CharField(default='BG010101010110', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier_eik',
            field=models.CharField(default='000000000', max_length=13),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='whole_price_with_dds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='whole_price_without_dds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
