# Generated by Django 5.1.6 on 2025-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_alter_invoice_dds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='supplier_dds',
            field=models.CharField(default='BG000000000', max_length=20),
        ),
    ]
