# Generated by Django 5.1.6 on 2025-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_alter_invoice_supplier_dds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DDS',
            field=models.CharField(choices=[('20', '20'), ('9', '9'), ('0', '0')], default='20', max_length=20),
        ),
    ]
