# Generated by Django 5.1.6 on 2025-06-14 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_invoice_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
