# Generated by Django 5.1.6 on 2025-04-15 13:30

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new_vendor', max_length=100)),
                ('phone_number', models.CharField(max_length=100, validators=[common.validators.AllNumbersValidator, common.validators.TenCharactersValidator])),
                ('additional_information', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
