# Generated by Django 5.1.6 on 2025-04-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='new_vendor', max_length=100),
        ),
    ]
