# Generated by Django 5.1.6 on 2025-04-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_app', '0002_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='additional_information',
            field=models.TextField(default='', max_length=500),
        ),
    ]
