# Generated by Django 5.0.7 on 2025-08-04 14:57

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_app', '0002_vendor_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='ZIP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='asdasd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(default='asdasd@abv.bg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='fax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='first_name',
            field=models.CharField(default='conor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='job_title',
            field=models.CharField(default='jlob', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_name',
            field=models.CharField(default='carlsen', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='personal_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[common.validators.AllNumbersValidator, common.validators.TenCharactersValidator]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='web_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
