# Generated by Django 5.0.7 on 2025-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_app', '0003_remove_vendor_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
