# Generated by Django 5.1.6 on 2025-06-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='phone_number',
            field=models.CharField(default=1898602996, max_length=11),
            preserve_default=False,
        ),
    ]
