# Generated by Django 5.1.6 on 2025-05-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_alter_orderproduct_unique_together_order_order_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_name',
        ),
    ]
