# Generated by Django 5.1.6 on 2025-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_remove_order_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('returned', 'returned'), ('refunded', 'refunded')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('bank transfer', 'bank transfer'), ('other', 'other')], default='cash', max_length=15),
        ),
    ]
