# Generated by Django 5.1.6 on 2025-04-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_order_client_order_employee_order_shipper_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
