# Generated by Django 5.0.7 on 2025-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_app', '0004_rename_name_shipper_address_remove_shipper_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
