# Generated by Django 5.1.6 on 2025-07-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0007_alter_order_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='pending', max_length=15),
        ),
    ]
