# Generated by Django 5.0.7 on 2025-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0008_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='pending', max_length=15),
        ),
    ]
