# Generated by Django 5.1.6 on 2025-04-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='orders',
        ),
    ]
