# Generated by Django 5.0.7 on 2025-08-04 11:06

import common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0002_client_added_at'),
        ('invoice_app', '0010_remove_invoice_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ZIP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='business_phone',
            field=models.CharField(default=1234567890, max_length=100, validators=[common.validators.AllNumbersValidator, common.validators.TenCharactersValidator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_app.company'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='job_title',
            field=models.CharField(default='job_title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[common.validators.AllNumbersValidator, common.validators.TenCharactersValidator]),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='web_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
