# Generated by Django 5.0.7 on 2025-08-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0003_client_zip_client_business_phone_client_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='personal_phone',
            new_name='personal_phone_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='business_phone',
        ),
    ]
