# Generated by Django 5.1.6 on 2025-06-14 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0002_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
