# Generated by Django 5.1.6 on 2025-05-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_version',
            field=models.SmallIntegerField(default=1),
        ),
    ]
