# Generated by Django 5.0.7 on 2025-08-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0004_rename_personal_phone_client_personal_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
