# Generated by Django 5.0.7 on 2025-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0006_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
