# Generated by Django 5.1.6 on 2025-04-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='current_products_being_shipped',
        ),
    ]
