# Generated by Django 5.0.7 on 2025-08-04 14:48

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_app', '0003_shipper_added_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipper',
            old_name='name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='salary',
        ),
        migrations.AddField(
            model_name='shipper',
            name='ZIP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='email',
            field=models.CharField(default='asdasd@abv.bg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='fax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='first_name',
            field=models.CharField(default='emanuel', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='job_title',
            field=models.CharField(default='job', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='last_name',
            field=models.CharField(default='gogogo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='personal_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[common.validators.AllNumbersValidator, common.validators.TenCharactersValidator]),
        ),
        migrations.AddField(
            model_name='shipper',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='web_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[common.validators.AllNumbersValidator, common.validators.TenCharactersValidator]),
        ),
    ]
