# Generated by Django 5.1.6 on 2025-06-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_alter_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
